services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: pruebas
      POSTGRES_PASSWORD: pruebas
      POSTGRES_DB: pruebas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: